"""initial migration

Revision ID: 28f605329a82
Revises: e49bcd3fe627
Create Date: 2025-09-22 08:56:59.319102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28f605329a82"
down_revision: Union[str, None] = "e49bcd3fe627"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "week_activities", sa.Column("equipment", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "week_activities",
        sa.Column("equipment_done", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "week_activities",
        sa.Column("instructions", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "week_activities",
        sa.Column("instructions_done", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "week_activities", sa.Column("adhd_tips", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "week_activities",
        sa.Column("adhd_tips_done", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("week_activities", "adhd_tips_done")
    op.drop_column("week_activities", "adhd_tips")
    op.drop_column("week_activities", "instructions_done")
    op.drop_column("week_activities", "instructions")
    op.drop_column("week_activities", "equipment_done")
    op.drop_column("week_activities", "equipment")
    # ### end Alembic commands ###
