"""initial migration

Revision ID: 3c19bdfcfc97
Revises: 
Create Date: 2025-09-22 09:05:44.210980

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c19bdfcfc97"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("google_id", sa.String(length=100), nullable=True),
        sa.Column("google_avatar_url", sa.String(length=500), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zipcode", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_updated_at", sa.DateTime(), nullable=True),
        sa.Column("location_accuracy", sa.Float(), nullable=True),
        sa.Column("family_size", sa.Integer(), nullable=True),
        sa.Column("adults_count", sa.Integer(), nullable=True),
        sa.Column("has_car", sa.Boolean(), nullable=False),
        sa.Column("max_travel_distance", sa.Integer(), nullable=True),
        sa.Column("weekly_activity_budget", sa.Float(), nullable=True),
        sa.Column("max_activities_per_week", sa.Integer(), nullable=False),
        sa.Column("family_profile_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("premium_subscription", sa.Boolean(), nullable=True),
        sa.Column("premium_subscription_started_at", sa.DateTime(), nullable=True),
        sa.Column("premium_subscription_expires_at", sa.DateTime(), nullable=True),
        sa.Column("premium_subscription_tier", sa.String(length=50), nullable=True),
        sa.Column("premium_subscription_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_city"), "users", ["city"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_zipcode"), "users", ["zipcode"], unique=False)
    op.create_table(
        "family_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "preferred_themes",
            sa.ARRAY(
                postgresql.ENUM(
                    "ADVENTURE",
                    "CREATIVE",
                    "EDUCATIONAL",
                    "FITNESS",
                    "FOOD_DRINK",
                    "FESTIVE",
                    "MINDFULNESS",
                    "NATURE",
                    "RELAXATION",
                    "SOCIAL",
                    name="theme_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "preferred_activity_types",
            sa.ARRAY(
                postgresql.ENUM(
                    "AMUSEMENT_PARK",
                    "ARTS_CRAFTS",
                    "BOARD_GAMES",
                    "CLASSES",
                    "DANCE",
                    "FESTIVAL",
                    "GAMES",
                    "GARDENING",
                    "HIKING",
                    "INDOOR",
                    "MUSIC",
                    "OUTDOOR",
                    "PARK",
                    "PUZZLES",
                    "SCIENCE_TECH",
                    "STORYTELLING",
                    "TRAVEL",
                    "VIDEO_GAMES",
                    "VOLUNTEERING",
                    "SPORTS",
                    "ZOO_AQUARIUM",
                    name="activity_type_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "preferred_cost_ranges",
            sa.ARRAY(
                postgresql.ENUM("FREE", "LOW", "MEDIUM", "HIGH", name="cost_enum")
            ),
            nullable=True,
        ),
        sa.Column(
            "preferred_locations",
            sa.ARRAY(
                postgresql.ENUM(
                    "HOME_INDOOR",
                    "HOME_OUTDOOR",
                    "LOCAL",
                    "REGIONAL",
                    "TRAVEL",
                    name="location_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "available_days",
            sa.ARRAY(
                postgresql.ENUM(
                    "SUNDAY",
                    "MONDAY",
                    "TUESDAY",
                    "WEDNESDAY",
                    "THURSDAY",
                    "FRIDAY",
                    "SATURDAY",
                    name="days_of_week",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "preferred_time_slots",
            sa.ARRAY(
                postgresql.ENUM(
                    "MORNING", "AFTERNOON", "EVENING", name="preferred_time_slot"
                )
            ),
            nullable=True,
        ),
        sa.Column("group_activity_comfort", sa.String(length=20), nullable=True),
        sa.Column("new_experience_openness", sa.String(length=20), nullable=True),
        sa.Column("educational_priorities", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("equipment_owned", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("accessibility_needs", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("special_requirements", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_family_preferences_user_id"),
        "family_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "kids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("dob", sa.DATE(), nullable=True),
        sa.Column("interests", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("special_needs", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kids_id"), "kids", ["id"], unique=False)
    op.create_index(op.f("ix_kids_parent_id"), "kids", ["parent_id"], unique=False)
    op.create_table(
        "user_behavior_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("marking_rate", sa.Float(), nullable=False),
        sa.Column("marks_big_activities_only", sa.Boolean(), nullable=False),
        sa.Column("big_activity_marking_rate", sa.Float(), nullable=False),
        sa.Column("small_activity_marking_rate", sa.Float(), nullable=False),
        sa.Column("successful_themes", sa.JSON(), nullable=True),
        sa.Column("successful_activity_types", sa.JSON(), nullable=True),
        sa.Column("successful_cost_ranges", sa.JSON(), nullable=True),
        sa.Column("successful_durations", sa.JSON(), nullable=True),
        sa.Column("weather_sensitivity", sa.Float(), nullable=False),
        sa.Column("seasonal_patterns", sa.JSON(), nullable=True),
        sa.Column("last_calculated", sa.DateTime(), nullable=False),
        sa.Column("calculation_confidence", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_verified", sa.Boolean(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("location_verified", sa.Boolean(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "primary_type",
            postgresql.ENUM(
                "AMUSEMENT_PARK",
                "ARTS_CRAFTS",
                "BOARD_GAMES",
                "CLASSES",
                "DANCE",
                "FESTIVAL",
                "GAMES",
                "GARDENING",
                "HIKING",
                "INDOOR",
                "MUSIC",
                "OUTDOOR",
                "PARK",
                "PUZZLES",
                "SCIENCE_TECH",
                "STORYTELLING",
                "TRAVEL",
                "VIDEO_GAMES",
                "VOLUNTEERING",
                "SPORTS",
                "ZOO_AQUARIUM",
                name="activity_type_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "primary_theme",
            postgresql.ENUM(
                "ADVENTURE",
                "CREATIVE",
                "EDUCATIONAL",
                "FITNESS",
                "FOOD_DRINK",
                "FESTIVE",
                "MINDFULNESS",
                "NATURE",
                "RELAXATION",
                "SOCIAL",
                name="theme_enum",
            ),
            nullable=True,
        ),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("llm_generated", sa.Boolean(), nullable=True),
        sa.Column("equipment", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("instructions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("adhd_tips", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_kid_id", sa.Integer(), nullable=True),
        sa.Column(
            "costs",
            sa.ARRAY(
                postgresql.ENUM("FREE", "LOW", "MEDIUM", "HIGH", name="cost_enum")
            ),
            nullable=True,
        ),
        sa.Column(
            "durations",
            sa.ARRAY(
                postgresql.ENUM(
                    "SHORT",
                    "MEDIUM",
                    "LONG",
                    "FULL_DAY",
                    "MULTI_DAY",
                    name="duration_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "participants",
            sa.ARRAY(
                postgresql.ENUM(
                    "SOLO",
                    "TWO_PLAYER",
                    "SMALL_GROUP",
                    "MEDIUM_GROUP",
                    "LARGE_GROUP",
                    "FAMILY",
                    name="participants_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "locations",
            sa.ARRAY(
                postgresql.ENUM(
                    "HOME_INDOOR",
                    "HOME_OUTDOOR",
                    "LOCAL",
                    "REGIONAL",
                    "TRAVEL",
                    name="location_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "seasons",
            sa.ARRAY(
                postgresql.ENUM(
                    "ALL",
                    "SPRING",
                    "SUMMER",
                    "FALL",
                    "WINTER",
                    "RAINY_DAY",
                    "SNOWY_DAY",
                    name="season_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "age_groups",
            sa.ARRAY(
                postgresql.ENUM(
                    "TODDLER",
                    "CHILD",
                    "TWEEN",
                    "TEEN",
                    "ADULT",
                    "FAMILY",
                    name="age_group_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "frequency",
            sa.ARRAY(
                postgresql.ENUM(
                    "DAILY",
                    "MULTIPLE_TIMES_WEEK",
                    "WEEKLY",
                    "BIWEEKLY",
                    "MONTHLY",
                    "SEVERAL_TIMES_YEAR",
                    "SEASONAL",
                    "ANNUALLY",
                    name="frequency_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "themes",
            sa.ARRAY(
                postgresql.ENUM(
                    "ADVENTURE",
                    "CREATIVE",
                    "EDUCATIONAL",
                    "FITNESS",
                    "FOOD_DRINK",
                    "FESTIVE",
                    "MINDFULNESS",
                    "NATURE",
                    "RELAXATION",
                    "SOCIAL",
                    name="theme_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "activity_types",
            sa.ARRAY(
                postgresql.ENUM(
                    "AMUSEMENT_PARK",
                    "ARTS_CRAFTS",
                    "BOARD_GAMES",
                    "CLASSES",
                    "DANCE",
                    "FESTIVAL",
                    "GAMES",
                    "GARDENING",
                    "HIKING",
                    "INDOOR",
                    "MUSIC",
                    "OUTDOOR",
                    "PARK",
                    "PUZZLES",
                    "SCIENCE_TECH",
                    "STORYTELLING",
                    "TRAVEL",
                    "VIDEO_GAMES",
                    "VOLUNTEERING",
                    "SPORTS",
                    "ZOO_AQUARIUM",
                    name="activity_type_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "activity_scale",
            postgresql.ENUM(
                "SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE", name="activity_scale_enum"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_kid_id"], ["kids.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_assigned_to_kid_id"),
        "activities",
        ["assigned_to_kid_id"],
        unique=False,
    )
    op.create_index(op.f("ix_activities_id"), "activities", ["id"], unique=False)
    op.create_index(
        op.f("ix_activities_user_id"), "activities", ["user_id"], unique=False
    )
    op.create_table(
        "activity_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("suggested_date", sa.Date(), nullable=False),
        sa.Column("target_week_start", sa.Date(), nullable=False),
        sa.Column("suggested_reason", sa.Text(), nullable=True),
        sa.Column("completion_status", sa.String(length=20), nullable=False),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("inferred_completion_likelihood", sa.Float(), nullable=True),
        sa.Column("weather_conditions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activity_suggestions_activity_date",
        "activity_suggestions",
        ["activity_id", "suggested_date"],
        unique=False,
    )
    op.create_index(
        "idx_activity_suggestions_user_date",
        "activity_suggestions",
        ["user_id", "suggested_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_suggestions_activity_id"),
        "activity_suggestions",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_suggestions_suggested_date"),
        "activity_suggestions",
        ["suggested_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_suggestions_target_week_start"),
        "activity_suggestions",
        ["target_week_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_suggestions_user_id"),
        "activity_suggestions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "week_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("llm_notes", sa.String(), nullable=True),
        sa.Column("llm_suggestion", sa.Boolean(), nullable=True),
        sa.Column("equipment", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("equipment_done", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("instructions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("instructions_done", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("adhd_tips", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("adhd_tips_done", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "activity_id", "year", "week", name="uq_user_activity_week"
        ),
    )
    op.create_index(
        op.f("ix_week_activities_activity_id"),
        "week_activities",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_week_activities_user_id"), "week_activities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_week_activities_user_id"), table_name="week_activities")
    op.drop_index(op.f("ix_week_activities_activity_id"), table_name="week_activities")
    op.drop_table("week_activities")
    op.drop_index(
        op.f("ix_activity_suggestions_user_id"), table_name="activity_suggestions"
    )
    op.drop_index(
        op.f("ix_activity_suggestions_target_week_start"),
        table_name="activity_suggestions",
    )
    op.drop_index(
        op.f("ix_activity_suggestions_suggested_date"),
        table_name="activity_suggestions",
    )
    op.drop_index(
        op.f("ix_activity_suggestions_activity_id"), table_name="activity_suggestions"
    )
    op.drop_index(
        "idx_activity_suggestions_user_date", table_name="activity_suggestions"
    )
    op.drop_index(
        "idx_activity_suggestions_activity_date", table_name="activity_suggestions"
    )
    op.drop_table("activity_suggestions")
    op.drop_index(op.f("ix_activities_user_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_assigned_to_kid_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_table("user_behavior_analytics")
    op.drop_index(op.f("ix_kids_parent_id"), table_name="kids")
    op.drop_index(op.f("ix_kids_id"), table_name="kids")
    op.drop_table("kids")
    op.drop_index(
        op.f("ix_family_preferences_user_id"), table_name="family_preferences"
    )
    op.drop_table("family_preferences")
    op.drop_index(op.f("ix_users_zipcode"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_city"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
