"""initial migration

Revision ID: 98e6d51506ea
Revises: 
Create Date: 2025-09-18 19:43:21.831503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e6d51506ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('equipment', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('activities', sa.Column('instructions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('activities', sa.Column('adhd_tips', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('premium_subscription', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('premium_subscription_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('premium_subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('premium_subscription_tier', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('premium_subscription_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_subscription_tokens')
    op.drop_column('users', 'premium_subscription_tier')
    op.drop_column('users', 'premium_subscription_expires_at')
    op.drop_column('users', 'premium_subscription_started_at')
    op.drop_column('users', 'premium_subscription')
    op.drop_column('activities', 'adhd_tips')
    op.drop_column('activities', 'instructions')
    op.drop_column('activities', 'equipment')
    # ### end Alembic commands ###
